### ISSUE TITLE
explore urls do not work with advanced params

### ISSUE THREAD

**Issue by whizzzkid** [whizzzkid/instagram-reverse-proxy#12]
While https://igpi.ga/whizzzkid/?__a=1 works fine.

This url https://www.instagram.com/explore/locations/1028292354/?__a=1 fails to work as https://igpi.ga/explore/locations/1028292354/?__a=1 however this feature works fine local.

**Comment by ravindra9278** [comment]
I am getting error
 
code | 5
desc | "Referer was denied access."

**Comment by whizzzkid** [comment]
@ravindra9278  this issue has been discussed in #14 Please do not spam other issues.

**Comment by whizzzkid** [comment]
These now work, demo https://jsfiddle.net/2rcxz51x/3/
