### ISSUE TITLE
Referrer and localhost

### ISSUE THREAD

**Issue by drunkenclam** [whizzzkid/instagram-reverse-proxy#13]
Hi,

first, thanks for creating this great service!

Since the update yesterday, that requires a referrer, I'm no longer able to use it from localhost (sends no referrer). Any chance to change this?

**Comment by whizzzkid** [comment]
If you're running the proxy on localhost then simply run the dev instance:

    $ npm run dev

The proxy should be live on 127.0.0.1:3000/... and would work with undefined referrer. Anyways the prod proxy should honor all requests from local web project. As a matter of fact I can see lot of queries from local projects as of now.

Hope this helps
