### ISSUE TITLE
Denying request from referer: undefined 

### ISSUE THREAD

**Issue by Nuneshere** [whizzzkid/instagram-reverse-proxy#14]
Hey whizzkid,

i Might just missed some changes here, but that's what i'm getting from the url that, previously, was working just fine.
see samples : https://igpi.ga/loganpaul/media  https://igapi.ga/loganpaul/media https://igpi.ga/loganpaul/?__a=1

Just want to say a HUGE thanks for this man, i'm fucking happy that you build this and i'm working on some really nice projects with it.

**Comment by whizzzkid** [comment]
You're welcome :)

You're supposed to see undefined on prod, but this will not hamper your website where you use this. As an example, try clicking the links above, the browser will append this page as the referrer for the request and it will load data. If you try copy-pasting this into the address bar, then the referrer will be undefined and it won't load anything.

As an example see my blog https://nishantarora.in/ I am loading instagram images just fine and it will continue to work as my blog is the referrer for the request. 

Read more about referer header here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

**Comment by vinicoder** [comment]
Hi whizzkid,

I really enjoyed your application! I also have the same problem, until I entered your blog to see, but it is also out.

**Comment by napcat** [comment]
I'm also getting the {"code":5,"desc":"Referer was denied access."} when trying to access some public public profiles and bussiness pages.

**Comment by whizzzkid** [comment]
@napcat that's because your request is missing the referrer header. It works here http://plnkr.co/edit/4oCwpbMm6p9cyJb1UWld?p=preview and https://nishantarora.in

**Comment by eliaspizarro** [comment]
I got this response :/

{"code":5,"desc":"Referer was denied access."}

```
  <script>
	var usuario = "liqanantai";
    $.ajax({
      url: "https://igpi.ga/".usuario."/media",
      dataType: "jsonp",
      data: {
        count: 3
      },
      success: function(json) {
		console.log(json);
        for (var i in json.posts) {
          var img = document.createElement("IMG");
          img.src = json.posts[i].display_url;
          img.width = '320';
          document.body.appendChild(img);
        }
      }
    });
  </script>	
```

**Comment by whizzzkid** [comment]
@eliaspizarro There are only two reasons you are getting this response:

* Reason 1: you did not read this [wiki](https://github.com/whizzzkid/instagram-proxy-api/wiki/Why-am-I-getting-referrer-undefined)

* Reason 2: The website you're using it on is [blacklisted](https://github.com/whizzzkid/instagram-proxy-api/blob/master/blacklist.js). In which case you would have received a 24-hour notice before being blacklisted. 

Either way I will not be able to help you because the proxy is working fine.
