### ISSUE TITLE
Request for more endpoints

### ISSUE THREAD

**Issue by sonesson89** [whizzzkid/instagram-reverse-proxy#19]
First of all, thank you for an amazing API!

I am wondering if it would possible to create one or more endpoints for fetching more data about a specific post. I know that for the official instagram API that I tried a while back it was possible to see hashtags for a post, also you could see the position (in coordinates). You could also view the filter used for a post. Would it be possible to see any of this information with your API?

**Comment by whizzzkid** [comment]
well that means you have not understood the API at all, the aim here is to make as much data from IG public as possible. But whatever information you're asking for is already provided.

[Demo](https://jsfiddle.net/2rcxz51x/2/) So let's say you're browsing a user's post: https://igpi.ga/whizzzkid/media/?count=3
 
[Demo](https://jsfiddle.net/2rcxz51x/1/) You now have the post shortcode which you can use to get post info: https://igpi.ga/p/BbswoeABkT8/?__a=1

[Demo](https://jsfiddle.net/2rcxz51x/3/) This should actually provide you with the location id which can be used like: https://igpi.ga/explore/locations/414326164/?__a=1

This is exactly what the API does but not exactly convenient. This will require you to send in 3 requests for each lat/lng for the post, if I were to write a method to do exactly that, it will slow the overall api and I'll have to send calls to ig 3 times.

**Comment by whizzzkid** [comment]
Added as wiki page https://github.com/whizzzkid/instagram-proxy-api/wiki/Getting-Post-Location-Data
