### ISSUE TITLE
"__typename": "GraphVideo" does not have video url (mp4) information

### ISSUE THREAD

**Issue by maciekdragan** [whizzzkid/instagram-reverse-proxy#20]
Last API (https://www.instagram.com/[username]/media/) had mp4 links for video media.
New one doesn't. How to get around this problem ?

**Comment by whizzzkid** [comment]
The new one actually just returns the posts and it's thumbnails, that's how ig works now. Once you have the post shortcode use that to hit the proxy again like https://igpi.ga/p/BYrmGN4AWjE/?__a=1 and you should have the mp4 link as video_url, [demo here](https://jsfiddle.net/2rcxz51x/5/)
