### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 ()

### ISSUE THREAD

**Issue by ghost** [whizzzkid/instagram-reverse-proxy#21]
I have a problem sir, what could be the reason behind this error? My code works but suddenly I ended here, please respond. I'm using Google DevTools Console, and it says
>  No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 429.

**Comment by whizzzkid** [comment]
@larrianedev 429 is too many requests from your app. Follow this:

https://github.com/whizzzkid/instagram-proxy-api/wiki/Developing-on-Local
