### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by sonesson89** [whizzzkid/instagram-reverse-proxy#22]
Hi! I see that now all of the sudden you get temp banned due to rate limit after too many requests. My app tries to fetch all posts of a user to display some data about them, but now it starts failing for me after a few requests. Is it supposed to be like this?

**Comment by whizzzkid** [comment]
Yes, the rate limits are in effect, because someone was trying to scrape too much data from this api, this is not a dev api, prod api is getting penalized by IG because of this scraping. Please clone this repo and use a local version of this API to test on your system.

**Comment by dozzy100** [comment]
Talking of local version, in the source what is GRAPH_USER_QUERY_ID and GRAPH_TAG_QUERY_ID and how / where can I get those details for myself?

**Comment by whizzzkid** [comment]
@dozzy100 https://github.com/whizzzkid/instagram-proxy-api/blob/master/app.js#L35
