### ISSUE TITLE
https://igpi.ga/whizzzkid/media?count=3

### ISSUE THREAD

**Issue by croofec** [whizzzkid/instagram-reverse-proxy#26]
"code": 2,
"desc": "Failed to fetch from Instagram.",
"info": "encountered: TypeError: Cannot read property 'id' of undefinedfetched:

on https://igpi.ga/whizzzkid/media?count=3 and on my feed.

it looks like something has changed on instagram

**Comment by whizzzkid** [comment]
this is a duplicate of #25
