### ISSUE TITLE
Calls with max_id

### ISSUE THREAD

**Issue by sonesson89** [whizzzkid/instagram-reverse-proxy#27]
Calls with the "max_id" paramter no longer seems to be working.

This call:
https://instagramanalytics.herokuapp.com/martin.sonesson/?__a=1
works as intended but if I add the max_id paramter:
https://instagramanalytics.herokuapp.com/martin.sonesson/?__a=1&max_id=<max_id>

It just returns the exact same items in the "edge_owner_to_timeline_media" list. This has worked before. Do I need to use another endpoint now?

**Comment by sonesson89** [comment]
Never mind. I now realize I have to call /username/media. The response contains a link to the next page that looks something like /username/media?cursor=<next id>

**Comment by whizzzkid** [comment]
glad it worked out for you.
