### ISSUE TITLE
Advanced endpoints

### ISSUE THREAD

**Issue by moerphie** [whizzzkid/instagram-reverse-proxy#4]
I love your service.
But is there any way, that you can provide the following endpoints?

https://www.instagram.com/instagram/?__a=1
https://www.instagram.com/p/BUz99-GjeJ_/?__a=1

That would be awesome.

**Comment by KamilLelonek** [comment]
@moerphie what is `BUz99-GjeJ_` in case of the second one?

**Comment by moerphie** [comment]
@KamilLelonek Shortcode?!

**Comment by KamilLelonek** [comment]
Yep, I figured it out. Thanks!

**Comment by mdtahmid** [comment]
Hi, anyone found a solution to this? I'm trying to access the number of followers a person has (this information is public even on private profiles). It looks like with this API I can only access public media?
